services:
  postgres:
    image: postgres:17-alpine
    container_name: products-postgres
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - products-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: products-redis
    ports:
      - "6379:6379"

volumes:
  products-postgres-data:
