spring.application.name=PKCE-flow

app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/oauth2-demo}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID:oauth2-pkce-cookie-demo}

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}
