spring.application.name=authorization-code-flow

spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-id=oauth2-authorization-code-flow
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-secret=${AUTH_CODE_CLIENT_SECRET}
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.scope=openid,email,profile,roles
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.redirect-uri=http://localhost:8080/login/oauth2/code/oauth2-authorization-code-flow
spring.security.oauth2.client.provider.oauth2-authorization-code-flow.issuer-uri=http://localhost:8090/realms/oauth2-demo
